# Generated by Django 4.1.2 on 2022-10-25 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_celeb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(choices=[('D', 'Dawn'), ('N', 'Noon'), ('A', 'Afternoon'), ('E', 'Evening'), ('L', 'Latenight')], default='D', max_length=1)),
                ('tea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.tea')),
            ],
        ),
    ]
