# Generated by Django 4.1.2 on 2022-10-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_sighting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='date',
            field=models.DateField(verbose_name='Sighting Date'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='time',
            field=models.CharField(choices=[('D', 'Dawn'), ('N', 'Noon'), ('A', 'Afternoon'), ('E', 'Evening'), ('L', 'Latenight')], default='D', max_length=1, verbose_name='Time of day'),
        ),
    ]
