# Generated by Django 4.1.2 on 2022-10-26 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_sighting_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sighting',
            options={},
        ),
    ]
