# Generated by Django 4.1.2 on 2022-10-26 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_sighting_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tea',
            name='celebs',
            field=models.ManyToManyField(to='main_app.celeb'),
        ),
    ]
